JuliaPy/PythonCall.jl

- setup.py
Add a *setup.py* such that even pip of an old version can work ([reference](https://stackoverflow.com/questions/46205648/can-pip-install-from-setup-cfg-as-if-installing-from-a-requirements-file)).  See issue #38 .
> Python setup

- src/compat/multimedia.jl
This matches what PyPlot is [doing](https://github.com/JuliaPy/PyPlot.jl/blob/94366fcfd783e4467b9dae789c12a9762c87dcf3/src/PyPlot.jl#L100) too.
> crop whitespace around displayed figures

- Project.toml
Your `Project.toml` currently lists `julia = "1"`, but in my testing it seems that it requires Julia 1.6+ (and [your CI tests](https://github.com/cjdoris/PythonCall.jl/blob/b4528b71e9878c8a71b9bd48ff759b5d5b14267f/.github/workflows/tests.yml#L19) also require 1.6+).
In particular, you depend on MicroMamba.jl, which [also requires Julia 1.6+](https://github.com/cjdoris/MicroMamba.jl/blob/5f5c49780a0ae449becedc139be1c3ab244cec03/Project.toml#L12).   But if you try to install PythonCall on an earlier Julia version, it just pulls in an earlier version of MicroMamba (before [this commit](https://github.com/cjdoris/MicroMamba.jl/commit/51389e6ca4845f30c46bfe743d1b896caf6de6da)).
On earlier versions of Julia, I get errors like:
```jl
julia> using PythonCall
[ Info: Precompiling PythonCall …
```
> correct Julia minimum version to ≥ 1.6

- src/Py.jl
If you only define the 1-argument `hash(o::Py)`, then the 2-argument form `hash(o, h::UInt)` falls back to the generic `Base` method using `objectid(o)`, which is not what you want.
(Subtracting `- 3h` is what `Base.hash` typically does to mix hashes; I'm not sure if you want to do something fancier here?)
> define 2-arg Base.hash

- pysrc/juliacall/__init__.py
From issue https://github.com/cjdoris/PythonCall.jl/issues/175 some users have noticed that there is an issue with running the Juliacall python module on Apple.
Investigating the issue was found that the julia library load was causing the error.
From my report and thanks to the Julia community they pointed out that the library should be loaded in RTLD_GLOBAL mode (https://github.com/JuliaLang/julia/issues/45709)
> fix: Ensure julia lib is always loaded as global

- pysrc/juliacall/__init__.py
added support for --threads, --procs, --min-optlevel
Fixes #184
> pass settings from -Xjuliacall_ to julia

- Project.toml
- src/pywrap/PyPandasDataFrame.jl
Before this PR pandas tables were being constructed from `Tables.DictColumnTable` using an unordered dict for the columns.  This was leading to deprecation warnings [as seen here](https://github.com/JuliaData/Tables.jl/issues/294#issue-1364917637) but more importantly, it could result in the creation of table objects which would have content inconsistent with their schema.  I'm actually a bit unsure why this was not breaking far more spectacularly (**update:** it's because the methods provided by `DictColumnTable` make the ordering of the dict largely unnecessary, but it would still break if anything ever iterated over the columns in the dict.)
I used the `OrderedDict` constructor from within `Tables` for this so as not to have to add `OrderedCollections` as a dependency.
> fix deprecation and possible faulty construction of pandas tables

- docs/src/pythoncall.md
- src/cpython/context.jl
- test/context.jl
Hello,
We have run into a problem when using PythonCall with newer versions of TensorFlow.  In particular, TensorFlow requires newer versions of libstdc++ than what is bundled with Julia.  To partially solve this problem, we replace the bundled version of libstdc++ with the system (Ubuntu 22.04) version of libstdc++.
When using PythonCall and CondaPkg, PythonCall injects a version bound for libstdc++ into the conda operations.  The version bound is determined by the version of libstdc++ bundled in Julia.  In this PR, we find the bound at runtime, and allow the user to specify the version bound via an environment variable: ~`JULIA_CONDAPKG_LIBSTDCXX_VERSION_BOUND`~`JULIA_PYTHONCALL_LIBSTDCXX_VERSION_BOUND`.  For example, set the version bound via:
```julia …
```
> libstdcxx version-bounds

- src/jlwrap/any.jl
- src/jlwrap/array.jl
- src/jlwrap/dict.jl
- src/jlwrap/set.jl
- test/jlwrap.jl
> Jlvaluetruth

- docs/src/faq.md
- pysrc/juliacall/__init__.py
Hi @cjdoris , this PR is to allow a user to configure what is passed to `julia --handle-signals=<yes,no>`. I have just updated it to be in line with all the other CONFIG params, defaulting to `no` to retain backwards compatibility. 
Following discussion thread starting [here](https://github.com/cjdoris/PythonCall.jl/issues/219#issuecomment-1605087024), I have found that this is much more robust and clean way to allow for multi-threaded julia code than [my previous workaround](https://github.com/cjdoris/PythonCall.jl/issues/298#issuecomment-1589784428).
Related to #219 
Related to #298 
Related to #330
> allow user to configure opt_handle_signals

- src/cpython/jlwrap.jl
The `caught` exception can useful for tracking down sources of bugs, as was the case for myself earlier today.
> print caught exceptions when (de)serializing

- .github/workflows/docs.yml
- .github/workflows/docscleanuo.yml
- docs/Project.toml
- docs/customdocs.jl
- docs/make.jl
This PR aims to update the Documenter.jl version to `v1`, thus closes #359.
The `DocsNode` API changed significantly in `v1`, so we might need some help from @mortenpi to restore the previous functionality.
> Update `Documenter -> v1`

- pysrc/juliacall/__init__.py
Before
```sh
x@x pythoncall % python -c 'import torch; from torch.autograd import Function; import juliacall'
zsh: segmentation fault  python3 -c 
x@x pythoncall % be sad
zsh: command not found: be
```
After
```sh
x@x pythoncall % python -c 'import torch; from torch.autograd import Function; import juliacall'
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/juliacall/__init__.py:62: UserWarning: `torch` was loaded before the juliacall. This may cause a segfault. To avoid this, import `juliacall` *before* importing `torch`. For updates, see https://github.com/pytorch/pytorch/issues/78829
warnings.warn(
zsh: segmentation fault  python3 -c 
x@x pythoncall % python -c 'import juliacall; import torch; from torch.autograd import Function'
x@x
```
Helps with …
> Add warning and hint when loading torch before juliacall

- docs/src/faq.md
macOS M1/M2 is Tier 1: https://julialang.org/downloads/#supported_platforms so this PR removes the part from the FAQ about it being Tier 2.
(I also haven't encountered any issues with M1/M2 specifically, so I think it's on par in terms of reliability as the other platforms)
> Remove M1/M2 part from FAQ

- src/Convert/pyconvert.jl
I ran into the same issue as https://discourse.julialang.org/t/sympy-symbol-to-symbolics-jl-num-adding-a-rule/102915 and thus thought it may be helpful to add another example to the docstring.
> Add an example for `tname` for custom Python-to-Julia conversion rule

- src/C/context.jl
Before 
```
julia> ENV["JULIA_CONDAPKG_BACKEND"] = "Null"
"Null"
julia> using PythonCall
Precompiling PythonCall
1 dependency successfully precompiled in 6 seconds. 22 already precompiled.
┌ Warning: Python library "/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0" could not be opened.
└ @ PythonCall.C /opt/.julia/dev/PythonCall/src/C/context.jl:118
ERROR: InitError: ArgumentError: NULL library handle
Stacktrace:
[1] #dlsym#1
@ ./libdl.jl:57
[2] dlsym
@ ./libdl.jl:56 [inlined]
[3] init_pointers(p::PythonCall.C.CAPIPointers, lib::Ptr{Nothing})
@ PythonCall.C /opt/.julia/dev/PythonCall/src/C/pointers.jl:282
[4] init_pointers
@ /opt/.julia/dev/PythonCall/src/C/pointers.jl:282 [inlined]
[5] init_context()
@ PythonCall.C /opt/.julia/dev/PythonCall/src/C/context.jl:138
[6] __init__()
@ …
```
> Ensure error message shows for missing libpython

- src/Core/Core.jl
- test/Core.jl
> Hot fix for #479

- src/Utils/Utils.jl
- test/Utils.jl
> fix issue 487

- src/Compat/serialization.jl
Looking into the documentation it looks like PythonCall uses Environment Variables for configuration.
Hence I added a simple `"JULIA_PYTHONCALL_PICKLE"` Environment Variable which defaults to `"pickle"`. This way users like me can easily use a more complete serialization system, as "pickle" cannot serialize everything (e.g. precompiled code, which is my usecase).
> making it possible to use another package instead of `pickle` for serialization (e.g. `dill`)

- pysrc/juliacall/__init__.py
> call jl_atexit_hook when atexit

- docs/src/releasenotes.md
- src/Compat/multimedia.jl
- test/Core.jl
> check for null in multimedia show functions

- CondaPkg.toml
- Project.toml
Resolves #519 (at least for the specific case of OpenSSL)
Requires https://github.com/JuliaPy/CondaPkg.jl/pull/140
Similar to how ibstdcpp-ng is handled, this PR communicated to `CondaPkg.jl` that we need a version of openssl that is compatible with one version potentially loaded via `OpenSSL_jll`
> Require a compatible openssl version

- src/GIL/GIL.jl
I think "unlock" is a typo and should be "lock". 
Hence, a GIL lock "locks, computes, unlocks" rather than "unlocks, computes, unlocks" unless there is something I'm missing. 
Nice work on the GIL by the way !
> Update GIL.jl lock's documentation (possible mistake?)

- src/GC/GC.jl
- test/JlWrap.jl
closes https://github.com/JuliaPy/PythonCall.jl/issues/543, closes https://github.com/JuliaPy/PythonCall.jl/pull/541
I added a test that would catch the issue:
```julia
julia> let arr = PyObjectArray([pylist([1]), pylist([2])])
PythonCall.JlWrap.pyobjectarray_finalizer(arr)
end
ERROR: UndefVarError: `PYNULL` not defined
Stacktrace:
[1] enqueue_all(ptrs::Vector{Ptr{PythonCall.C.PyObject}})
@ PythonCall.GC ~/PythonCall.jl/src/GC/GC.jl:106
[2] pyobjectarray_finalizer(x::PyObjectVector)
@ PythonCall.JlWrap ~/PythonCall.jl/src/JlWrap/objectarray.jl:30
[3] top-level scope
@ REPL[17]:2
```
> fix PyNULL typo

- src/Wrap/PyList.jl
- test/Wrap.jl
Julia 1.11 handles pushfirst! with multiple args differently and fails if no prepend! is defined.
This PR defines the appropriate prepend! method and adds respective tests.
> PyList: fix pushfirst! for Julia 1.11, by adding prepend!

- docs/src/releasenotes.md
- src/Wrap/PyArray.jl
- test/Wrap.jl
> Add `elsize` method for PyArray

- .github/workflows/tests.yml
- src/C/extras.jl
- src/Compat/pycall.jl
- src/Convert/ctypes.jl
- src/Convert/numpy.jl
- src/Convert/pyconvert.jl
- src/Convert/rules.jl
- src/Core/Py.jl
- src/Core/builtins.jl
- src/Core/err.jl
- src/JlWrap/C.jl
- src/JlWrap/base.jl
- src/JlWrap/io.jl
- src/JlWrap/objectarray.jl
- src/Wrap/PyArray.jl
Defines an `unsafe_convert` rule for `Py` to `C.PyPtr` so we can pass `Py` directly to C functions.
Also defines `incref(::Py)` so we don't have to operate on pointers.
Generalises our faked C functions in `extras.jl` to also allow `::Py` arguments in place of `::PyPtr`.
Fixes #617 - and more generally removes a lot of places where the Julia GC could have freed a `Py` while we still have a pointer to the Python object, causing a read-after-free error.
> use getptr a lot less

- .github/workflows/tests-nightly.yml
- .github/workflows/tests.yml
This PR improves the clarity of GitHub Actions job names by:
- Changing Julia job names from Test (os, julia version) to Test Julia (version, os)
- Changing Python job names from Test (os, python version) to Test Python (version, os)
- Simplifying Python version matrix from >=3.8 to 3 for cleaner job names
- Updating nightly test job names similarly
**Before:**
- Test (ubuntu-latest, julia 1.9)
- Test (ubuntu-latest, python >=3.8)
**After:**
- Test Julia (1.9, ubuntu-latest)
- Test Python (3, ubuntu-latest)
This makes it much easier to quickly identify which language and version is being tested when looking at the GitHub Actions dashboard.
> Improve GitHub workflow job names for better clarity

- src/Compat/gui.jl
- test/Compat.jl
This PR adds PySide6 support to the GUI compatibility layer.
- **Updated `fix_qt_plugin_path() function** to support both Qt5 and Qt6 configurations:
- Added support for qt6.conf files used by PySide6 (in addition to existing qt.conf support)
- For Qt6, reads the Libraries entry instead of Prefix 
- Sets QT_PLUGIN_PATH to {libraries}/qt6/plugins for PySide6 compatibility
- Maintains backward compatibility with existing Qt5 frameworks
- **Added PySide6 to event loop callback** by including it in the supported GUI frameworks list and adding the import for PySide6.QtCore
- **Added PySide6 module hook** to automatically call `fix_qt_plugin_path() when PySide6 is imported
- **Updated documentation** to include PySide6 in all relevant docstrings and parameter descriptions
The key insight from …
> Add PySide6 support to gui.jl

- .github/workflows/tests.yml
- src/C/consts.jl
Hopefully fixes this issue: https://github.com/JuliaPy/PythonCall.jl/issues/641#issuecomment-3075086581
> Test with PYTHON_JULIACALL_HANDLE_SIGNALS=yes

- docs/src/releasenotes.md
- pysrc/juliacall/juliapkg.json
- src/C/consts.jl
- src/C/pointers.jl
- src/JlWrap/C.jl
This PR implements the suggestion from @ZeroIntensity to switch from static PyTypeObject structures to heap-allocated types using PyType_FromSpec.
- **Added PyType_Spec and PyType_Slot structs** to C API bindings in src/C/consts.jl
- **Added all Python type slot constants** from 	ypeslots.h for proper slot definitions
- **Converted PyJuliaBase_Type creation** from manual PyTypeObject to PyType_FromSpec in src/JlWrap/C.jl
- **Used __weaklistoffset__ member definition** for backward compatibility with older Python versions
- **Fixed PyType_FromSpec function signature** in src/C/pointers.jl
- **Avoids ABI compatibility issues** by using slot-based type definitions instead of structure fields
- **Future-proof approach** that works with different Python versions
- **Cleaner implementation** …
> Switch to heap types using PyType_FromSpec

- src/C/context.jl
- src/C/pointers.jl
- src/Core/err.jl
This PR removes dead code that was supporting old versions of Julia and Python:
**Changes:**
- Remove fallback to Py_Finalize() for Python < 3.6, always use Py_FinalizeEx()
- Update minimum Python version check from 3.5+ to 3.9+ (aligns with recent version bump)
- Remove Py_Finalize function signature, keeping only Py_FinalizeEx
- Simplify pointer initialization by removing conditional logic
- Remove Julia version check for stacktrace formatting (< 1.6.0), keep only modern formatting
**Files changed:**
- src/C/context.jl: Simplified finalization and version checking
- src/C/pointers.jl: Removed legacy function signatures  
- src/Core/err.jl: Removed legacy stacktrace formatting
Net reduction of 18 lines, making the codebase cleaner by removing compatibility shims that are no longer …
> Remove dead code supporting old versions of Julia/Python

- CondaPkg.toml
- Project.toml
- docs/src/releasenotes.md
Add libstdcxx to CondaPkg.toml with version "<=julia" to improve libstdc++ compatibility with the Julia toolchain. Bump CondaPkg compat to 0.2.30 to leverage related fixes. Update release notes to reflect the improved compatibility.
> build(deps): add libstdcxx pin, bump CondaPkg

- docs/src/faq.md
- docs/src/pythoncall.md
- docs/src/releasenotes.md
- src/C/context.jl
Add new option `@venv` to use a Python virtual environment located at `.venv` in the active project directory. Relative paths for `JULIA_PYTHONCALL_EXE` are now resolved relative to the active project. Includes documentation updates and release notes.
Closes #668.
> feat(exe): add support for @venv and relative paths in JULIA_PYTHONCALL_EXE

- docs/src/conversion-to-python.md
- docs/src/releasenotes.md
- src/Core/Py.jl
- src/Core/builtins.jl
Allow any string or integer to be converted to python
Specifically this adds methods `Py(::AbstractString)`, `Py(::AbstractChar)`, `Py(::Integer)`, `Py(::Rational{<:Integer})`, `Py(::AbstractRange{<:Integer})` whereas previously we only allowed the builtin Julia string, char and integer types.
Fixes #608
> Relax conversions to python
